box: 'Debian_7.3_32'
box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/debian-73-i386-virtualbox-puppet.box'
box_ip: '192.168.20.20'
project_name: 'projectname'
project_path: '/var/www/projectname'
project_webroot: '/var/www/projectname/web'
project_url: 'www.projectname.local'
project_template: 'symfony'